### ISSUE TITLE
support variables in make

### ISSUE THREAD

**Issue by mosheavni** [desdic/greyjoy.nvim#34]
sometimes you want to run make and add variable.
example:

```
make something version=latest
```

is it possible to add this feature so we could pass variables to make?

**Comment by desdic** [comment]
Yeah it should be possible ( it is if you just the command manually via the generic plugin) but it would be a long list if I scan for it so how do you prefer to specify the option? The list via Telescope is read-only currently

**Comment by desdic** [comment]
@mosheavni I have made a PR https://github.com/desdic/greyjoy.nvim/pull/35 that allows an edit of commands. Could you check out out to see if this is what you need/want?

**Comment by desdic** [comment]
Turns out this is quite buggy since its doesn't allow a plugin or group so I'll redo the PR and maybe create a new command  for it

**Comment by desdic** [comment]
`:Greyedit` will enable edit before a run and then be saved so `:Greyjoy` will be able to run it next time

**Comment by desdic** [comment]
Its released now
